### ISSUE TITLE
SAM file lacks an MD tag

### ISSUE THREAD

**Issue by dorie8** [dewyman/TALON#45]
Hi, I tried to use TALON to process the alignment file I got from minimap2. It's a sam file. 
`python talon.py \
--f /private/.../TALON/hg38mini1BD.csv \
--db /private/.../TALON/hg38v27_talon.db \
--build hg38v27 
--o /private/.../TALON/hg38tal1BD`

The csv file has the alignment file name. however when I ran it, it gave me 
```
Traceback (most recent call last):
  File "talon.py", line 2475, in <module>
    main()
  File "talon.py", line 2452, in main
    struct_collection, outprefix)
  File "talon.py", line 1694, in process_all_sam_files
    exon_annotations, abundance = annotate_sam_transcripts(sam, d_name, cursor, struct_collection, o)
  File "talon.py", line 1919, in annotate_sam_transcripts
    qc_metrics = check_read_quality(line, struct_collection)
  File "talon.py", line 2069, in check_read_quality
    raise ValueError("SAM transcript %s lacks an MD tag" % read_ID)
ValueError: SAM transcript 2d415520-3a14-44b9-af3c-1962ab413e36 lacks an MD tag
```

I am not sure what is happening here...

**Comment by dewyman** [comment]
Hello, 
Before annotating the transcripts, TALON filters the provided SAM reads by computing the coverage and identity of each alignment, then comparing them to a minimum threshold (tunable in the options). To do this, it requires the SAM reads to have an MD tag, which records deletions and mismatches of the sequence relative to the reference genome. If you add the option --MD to your minimap2 command, I believe it will include these tags for you in the output, and you will no longer get this error when running TALON. I'll try to confirm this for you tomorrow, but hope this helps in the mean time!

**Comment by dewyman** [comment]
Confirmed- I performed a Minimap2 run with the --MD option enabled, and the MD tags are present in the output formatted the way TALON expects!

**Comment by dorie8** [comment]
Got it! I just checked that minimap2 does have the --MD option. Thank you for the quick response it was really helpful!
